import type {Metadata} from 'next'
import {Noto_Sans, Playfair_Display} from 'next/font/google'
import './globals.css'
import {cn} from '@/lib/utils'
import {Nav} from '../components/nav'

const playfairDisplayHeading = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-heading'
})

const notoSans = Noto_Sans({subsets: ['latin'], variable: '--font-sans'})

export const metadata: Metadata = {
  title: {
    template: 'yorkejohn.dev :: %s',
    default: "yorkejohn.dev :: John's Personal Website"
  },
  description: 'Generated by create next app'
}

const htmlClasses = cn(
  'h-full',
  'antialiased',
  'font-sans',
  notoSans.variable,
  playfairDisplayHeading.variable,
  'dark'
)

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={htmlClasses}>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
