import type {Metadata} from 'next'
import {Nav} from '@/components'
import {fonts} from '@/lib/fonts'
import {cn} from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: {
    template: 'yorkejohn.dev :: %s',
    default: "yorkejohn.dev :: John's Personal Website"
  },
  description: 'Generated by create next app'
}

type LayoutProps = Readonly<{
  children: React.ReactNode
}>

const htmlClasses = cn('h-full', 'antialiased', 'font-sans', ...fonts, 'dark')

export default function RootLayout({children}: LayoutProps) {
  return (
    <html lang="en" className={htmlClasses}>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
