import type {Metadata} from 'next'
import {fonts} from '@/lib/fonts'
import type {LayoutProps} from '@/lib/types'
import {cn} from '@/lib/utils'

import './globals.css'
import './typography.css'

export const metadata: Metadata = {
  title: {
    template: 'yorkejohn.dev :: %s',
    default: "yorkejohn.dev :: John's Personal Website"
  },
  description: 'Generated by create next app'
}

const htmlClasses = cn('h-full', 'antialiased', 'font-sans', ...fonts, 'dark')

export default function RootLayout({children}: LayoutProps) {
  return (
    <html lang="en" className={htmlClasses}>
      {children}
    </html>
  )
}
